export const FLUTTER_HEALTH_ICONS = [
    { name: 'health_and_safety', label: 'Health and Safety' },
    { name: 'medical_services', label: 'Medical Services' },
    { name: 'wheelchair_pickup', label: 'Wheelchair' },
    { name: 'local_hospital', label: 'Hospital' },
    { name: 'medication', label: 'Medication' },
    { name: 'healing', label: 'Healing' },
    { name: 'elderly', label: 'Elderly Care' },
    { name: 'bed', label: 'Hospital Bed' },
    { name: 'medical_information', label: 'Medical Info' },
    { name: 'psychology', label: 'Psychology' },
    { name: 'person', label: 'Person' },
    { name: 'person_add', label: 'Add Person' },
    { name: 'person_outline', label: 'Person Outline' },
    { name: 'sick', label: 'Sick' },
    { name: 'spa', label: 'Spa' },
    { name: 'sports_score', label: 'Sports Medicine' },
    { name: 'hearing', label: 'Hearing' },
    { name: 'mic_none', label: 'Speech' },
    { name: 'smoking_rooms', label: 'Smoking Rooms' },
    { name: 'today', label: 'Today (Appointments)' },
    { name: 'timer', label: 'Timer (Medication)' },
    { name: 'watch_later', label: 'Watch Later' },
    { name: 'work', label: 'Work Health' },
    { name: 'yoga', label: 'Yoga' },
    { name: 'bloodtype', label: 'Blood Type' },
    { name: 'nature_people', label: 'Nature People' },
    { name: 'local_pharmacy', label: 'Pharmacy' },
    { name: 'camera_alt', label: 'Camera (Medical Imaging)' },
    { name: 'bubble_chart', label: 'Bubble Chart (Health Analytics)' },
    { name: 'accessibility', label: 'Accessibility' },
    { name: 'accessible', label: 'Accessible' },
    { name: 'app_settings_alt', label: 'App Settings' },
    { name: 'assistant', label: 'Virtual Assistant' },
    { name: 'assistant_photo', label: 'Assistant Photo' },
    { name: 'badge', label: 'Badge' },
  ];
  